### ISSUE TITLE
Feature Request: Option to customize intensity

### ISSUE THREAD

**Issue by JackCA** [niw/HapticKey#1]
Awesome project and works great so far. Nice work!

It would be really great to be able to customize the intensity of the feedback, possibly between low, medium (default), and high?

**Comment by niw** [comment]
Haptic feedback is triggered by using Apple’s private, undocumented API that has a set of predefined gaussian wave. The current implementation is using the most strong one that can trigger enough feedback to the hands, but technically it’s possible to have an option that changes the predefined gaussian wave, which may just not simply changing intensity but may trigger much waker feedback. Let me try.

**Comment by niw** [comment]
Implemented intensity selection (c278996cd6dff4a2846c200ce53603cc5597ea97).
Released [HapticKey 0.3.0](https://github.com/niw/HapticKey/releases/tag/0.3.0).

**Comment by JackCA** [comment]
@niw amazing!!! This is perfect, thank you
