### ISSUE TITLE
Trackpad gesture to open notification center doesn’t work

### ISSUE THREAD

**Issue by niw** [niw/HapticKey#16]
Report on Twitter
> Hey bro, I found a problem with the HapticKey app on mac, my laptop is MacBook Pro 15 2106 (macOS 10.13.3) when the app runs in the background, my mac's notification center cannot open by my trackpad with the gesture . It looks like a bug.    @niw
https://twitter.com/806448839/status/973524403509108737

**Comment by niw** [comment]
As I tested the latest version of HapticKey on MacBook Pro 2017 (15 inches), it works as expected and I couldn’t reproduce this behavior.

**Comment by niw** [comment]
Reply on Twitter
> I made a video for this. this app satisfied me an important requirement, and it is a very necessary function witch Apple should insert this (touch bar touch feedback) into macOS itself!    PS: after a quit the app about 10 mins my notification center works as normal. XD
> https://twitter.com/GeekLimites/status/974112438583881728

**Comment by zhangwujun666** [comment]
This issue has been disappeared after I update to macOS 10.13.4 :D

**Comment by niw** [comment]
Looks like the issue has been resolved on 10.13.4. I’m going to close this issue. If we observe this issue again, please reopen this.
