### ISSUE TITLE
Why no feedback on volume, brightness up / down

### ISSUE THREAD

**Issue by wrabit** [niw/HapticKey#31]
I'm getting no feedback when pressing up / down on the volume and screen brightness. Just wondered if I am missing anything or there is a reason why it was excluded? (keyboard setting "Expanded control strip"

**Comment by niw** [comment]
@wrabit Could you try using ”All Taps on Touch Bar” instead, that should respond all taps on any type of Touch Bar mode.

If you’re already using it, but not getting feedbacks, try next steps to allow HapticKey to get events from Touch Bar.
1. Open System Preferences from Apple menu.
2. Select Security & Privacy.
3. Select Privacy tab, then select Accessibility.
4. Tap lock icon then type password of your administration account.
5. Find HapticKey in the “Allow the apps below to control your computer” list.
6. Enable checkmark. If checkmark is already enabled, disable then enable.

Thank you!

**Comment by wrabit** [comment]
@niw yes working in that mode but it's not effective enough for me. Having feedback only on the buttons themselves provides the most uninterrupted experience, being able to use function keys without looking down or at a very swift glance. If its registering all touches then you can be pressing away without real acknowledgement you hit a button - causing great frustration!

Haptic Touch Bar does it but I thought I'd checkout any alternatives.

Is it difficult to do?

**Comment by niw** [comment]
@wrabit Ah, I see what you meant, so detecting UI elements on Touch Bar to make a feedback. That requires extra reverse engineering about their API... which I didn’t complete yet, and I think the request is same as #4 so I will close this and merge with it.

**Comment by wrabit** [comment]
Ok but just to note: I don't mean sliders, i mean using the incremental buttons - i am using the mode which emulates the original function keys - no slider.




---- On Mon, 23 Sep 2019 23:22:32 +0200 notifications@github.com wrote ----



@wrabit Ah, I see what you meant, so detecting UI elements on Touch Bar to make a feedback. That requires extra reverse engineering about their API... which I didn’t complete yet, and I think the request is same as #4 so I will close this and merge with it.

**Comment by niw** [comment]
@wrabit Sure! I understand that part! If I can separately implement one if them, I will open this later and update, but likely these are same that the app needs to understand some Touch Bar private APIs.
