### ISSUE TITLE
No sound when enable sound effect 

### ISSUE THREAD

**Issue by ukieTux** [niw/HapticKey#34]
No sound when enable sound effect in 10.5.1 Macbook Pro 2018

**Comment by niw** [comment]
@ukieTux Did you mean 10.15.1 (Catalina)?

**Comment by niw** [comment]
Confirmed that it makes a sound when tap down and tap up on macOS 10.15.1 on MacBook Pro (2017,) and I don't think it's different from the one in 2018. Please make volume loud to hear if it's actually not making sounds or not. It doesn't play loud effect intentionally.

**Comment by ukieTux** [comment]
@niw  yes, 10.15.1 Catalina
I was set sound to max and make sure when i tap down there no sound, just sound from trackpad not from speaker

**Comment by ukieTux** [comment]
i got sound when using headset, but no sound in speaker

**Comment by niw** [comment]
@ukieTux I see, that sounds like not application issue but probably system configuration issue.
Could you make sure that other alert sounds are coming from speaker?
I think you can test it in System Preferences, open Sound pane, then select Sound Effects tab and pick one of alert sounds in the list.

**Comment by ukieTux** [comment]
Great, thanks it's work
