### ISSUE TITLE
HapticKey not working on MacBook Pro with M1 Chip

### ISSUE THREAD

**Issue by AyAyRON123** [niw/HapticKey#42]
when I installed HapticKey it only worked with sounds and lights but no haptics. This may be because of the new chip but I'm not sure.

**Comment by tanpengsccd** [comment]
Yes it dosen't work,but sound Effect work.

**Comment by AyAyRON123** [comment]
Are the devs planning to make it work in the future? because from now on all MacBooks will run off of an M chip.

**Comment by niw** [comment]
@AyAyRON123 Plan to fix it soon yet need some help from MacBook Pro (M1, 2020) owner since I don’t have that specific hardware.

**Comment by AyAyRON123** [comment]
is there anyway that I could help>?

**Comment by niw** [comment]
@AyAyRON123 Thanks, I actually just got a help from @1024jp. I think current tip branch now supports MacBook Pro (M1, 2020.)

**Comment by AyAyRON123** [comment]
ok thanks

**Comment by niw** [comment]
As I mentioned on #44, I’ve uploaded a pre-build binary [HapticKey.app-cd221bc.zip](https://github.com/niw/HapticKey/files/5753630/HapticKey.app-cd221bc.zip) from current tip branch for testing.
This is also universal binary for both Intel and Apple Silicon.
