### ISSUE TITLE
Haptics still not working with M1 MacBook Pro

### ISSUE THREAD

**Issue by AyAyRON123** [niw/HapticKey#44]
I deleted HaptiKey and reinstalled it but its still not working for me? Also, are you thinking of making a tutorial video because it may be easier to setup if we see you do it?

**Comment by niw** [comment]
@AyAyRON123 The change is not reflected to the binary distributed only available in the source code.
Try this [HapticKey.app-cd221bc.zip](https://github.com/niw/HapticKey/files/5753630/HapticKey.app-cd221bc.zip) instead.
This is a pre-build binary from current tip branch for testing.
