### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by dlackty** [niw/HapticKey#46]
As #42 #43 have been merged, and M1 devices has been released for months. I think it's a good idea to release a version with those fixes?

**Comment by neronmoon** [comment]
@niw Please do!

**Comment by niw** [comment]
Yes! but I want to work a few things before releasing a new binary, hopefully I can find time to settle it soon!
Sorry for delaying release, mean a while, you can try this ad-hoc binary [HapticKey.app-cd221bc.zip](https://github.com/niw/HapticKey/files/5753630/HapticKey.app-cd221bc.zip) for testing.

**Comment by kikikiblue** [comment]
I installed HapticKey.app-cd221bc.zip on my Intel Macbook successfully. 
```MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)```

Haptic works well but the sound effect is not working. 
Even if I turned off the sound effect, when I touch esc, sound effect is still working with haptic. 

Anyway, I really appreciate this great app. 
Thanks!!

**Comment by niw** [comment]
Sorry for took a long time since last release but I just published the newer version also updated per-build binary.
Please find new binary in [Releases](https://github.com/niw/HapticKey/releases) page.
