### ISSUE TITLE
It seems that the app uses much more memory with trackpad events.

### ISSUE THREAD

**Issue by kailuo** [niw/HapticKey#5]
Just found this issue after using it for a couple of hours, the app used almost 400MB memory which ... reminds me the SourceKitService (😛 just kidding, it is doing great now)

So I dig into the code and found that the issue occurs only with trackpad events, when using a mouse the usage is around 10MB which seems to be normal.

This project is so cool by the way 🚀, thanks!

**Comment by niw** [comment]
Looks like there is a leaking memory when we use ”All Taps on Touch Bar” mode.

**Comment by kailuo** [comment]
Yeah, seems that the event created in eventTapCallback was not released.

**Comment by kailuo** [comment]
And after adding an autoreleasepool there, problem solved 😄

**Comment by niw** [comment]
Yes, it is. `-[NSEvent eventWithCGEvent:]` retains `CGEvent` and returns “returns an autoreleased NSEvent” as its header comment said.

**Comment by niw** [comment]
Okay, fixed on 7e56060c8c246b919102df3adcef416465f6f883.
Released [HapticKey 0.3.3](https://github.com/niw/HapticKey/releases/tag/0.3.3).

**Comment by niw** [comment]
Thank you for reporting!

**Comment by kailuo** [comment]
Cool! 👍
