### ISSUE TITLE
Does this work on a M1 Mac?

### ISSUE THREAD

**Issue by m1mbp** [niw/HapticKey#50]
I downloaded Haptic Keys on my M1 MacBook Pro and the app runs, but no haptics. I don't know what could be wrong.

**Comment by niw** [comment]
You need to use newer binary not released yet for now, but you can use [HapticKey.app-cd221bc.zip](https://github.com/niw/HapticKey/files/5753630/HapticKey.app-cd221bc.zip) for testing.
Sorry for inconvenience. See #42 for the details.

**Comment by m1mbp** [comment]
Thank you so much, it works like a charm now. Thanks again for making this wonderful app.

**Comment by carbongo** [comment]
Thank you. You are the best!

**Comment by niw** [comment]
Since 0.6.0 released with this change, I am going to close this issue.
