### ISSUE TITLE
Does this work on M1 and Monterey?

### ISSUE THREAD

**Issue by luluhoc** [niw/HapticKey#52]
> You need to use newer binary not released yet for now, but you can use [HapticKey.app-cd221bc.zip](https://github.com/niw/HapticKey/files/5753630/HapticKey.app-cd221bc.zip) for testing.
> Sorry for inconvenience. See #42 for the details.

Hey, I installed the version from your reply on M1 on Beta 1 Monterey sound effect works but no haptics any updates?

**Comment by niw** [comment]
I haven’t have setup for macOS 12 Monterey beta yet...
If it doesn’t work, it may need to have extra work for sure.

**Comment by gashead76** [comment]
Release 0.6.1 does not seem to work on any of the betas of Monterey so far. No sounds or haptics. I tried the [one from above](https://github.com/niw/HapticKey/files/5753630/HapticKey.app-cd221bc.zip) and sound worked, no haptics however.

**Comment by niw** [comment]
@luluhoc @gashead76 I think I fixed both issues now, please try one I posted on #56 and see if it works on your environment or not.

**Comment by niw** [comment]
These issues are fixed on [0.7.0](https://github.com/niw/HapticKey/releases/tag/0.7.0).
