### ISSUE TITLE
Haptics don't work with MacOS Monterey

### ISSUE THREAD

**Issue by SteepAtticStairs** [niw/HapticKey#56]
Hi,
I have been using HapticKey perfectly on my 2020 M1 Macbook Pro running Big Sur, but I just upgraded to Monterey today and the haptics are no longer working. The app installs fine, and the screen flash seems to work, but the haptics no longer do. This seems to be an issue with Monterey, because it stopped working as soon as I upgraded. I am using the latest pre-built binary on the github releases page. Any help would be appreciated, thanks.

**Comment by jawil003** [comment]
Same Issue here 😟

**Comment by niw** [comment]
Yes, sorry, I am aware of this issue, It's same as #52, not limited to M1, but Monterey changes its API and seems current approach is no longer working.

**Comment by niw** [comment]
@jawil003  @SteepAtticStairs OK, I think I made various changes to make it works on macOS Monterey and other version of macOS.
Please try [HapticKey.app-c92001a.zip](https://github.com/niw/HapticKey/files/7448226/HapticKey.app-c92001a.zip) and see if it works on your environment or not.
Thanks!

**Comment by jawil003** [comment]
@niw Awesome will try it out. Thank you.

**Comment by jawil003** [comment]
@niw It is working as expected.

**Comment by niw** [comment]
@jawil003 Thank you for the confirmation!

**Comment by SteepAtticStairs** [comment]
@niw Just tried it out, it works perfectly! Thanks so much!

**Comment by niw** [comment]
@SteepAtticStairs Thank you for the confirmation, I will release newer version soon with other changes.
